version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo Starting database update/create
      - CONFIGURATION=true bundle exec rails db:create
      - CONFIGURATION=true bundle exec rails db:migrate
  post_build:
    commands:
      - echo Finished migrations